name: Build and validate
on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build and validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/cache@v6
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: |
          corepack enable

          yarn workspaces focus --all --production
          yarn install --immutable

      - name: yarn validate:dependencies
        run: yarn validate:dependencies
        continue-on-error: true

      - name: yarn build
        run: yarn build

      - uses: actions/upload-artifact@v7
        with:
          name: dist artifacts
          path: dist
